name: build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'json'
          output: 'trivy-results.json'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: trivy-results
          path: trivy-results.sarif
          
      - name: Upload BOM to Dependency Track
        run: |
          curl -X 'POST' \
            'http://localhost:8080/api/v1/bom' \
            -H 'accept: */*' \
            -H 'X-API-Key: ${{ secrets.DEPENDENCY_TRACK_API_KEY_1 }}' \
            -H 'Content-Type: multipart/form-data' \
            -F 'project=[PROJECT_UUID]' \
            -F 'bom=@trivy-results.json'
